proxy_location: EveryNode

http_options:
  request_timeout_s: -1
  keep_alive_timeout_s: 400

applications:

- name: "default"
  route_prefix: "/"
  import_path: chaos_test.pinger:app_builder
  runtime_env:
    working_dir: https://github.com/ray-project/serve_workloads/archive/886d227a054cd2c8c9e866f6af4ad07143576937.zip

  args:
    receiver_service_name: YOUR_RECEIVER_SERVICE_NAME
    receiver_build_id: YOUR_RECEIVER_BUILD_ID
    receiver_compute_config_id: YOUR_RECEIVER_COMPUTE_CONFIG_ID
    receiver_gcs_external_storage_config: YOUR_RECEIVER_GCS_EXTERNAL_STORAGE_CONFIG
    pinger_service_name: YOUR_PINGER_SERVICE_NAME
    project_id: YOUR_PROJECT_ID
    receiver_qps: YOUR_RECEIVER_QPS
    pinger_qps: YOUR_PINGER_QPS
    kill_interval_s: YOUR_KILL_INTERVAL_S
    upgrade_interval_s: YOUR_UPGRADE_INTERVAL_S
    upgrade_types: List[str] = ["IN_PLACE", "ROLLOUT"]

  deployments:
  - name: Router
    num_replicas: 1
    ray_actor_options:
      num_cpus: 0
  - name: receiver_Pinger
    num_replicas: 1
    ray_actor_options:
      num_cpus: 0
  - name: self_Pinger
    num_replicas: 1
    ray_actor_options:
      num_cpus: 0
  - name: Reaper
    num_replicas: 1
    ray_actor_options:
      num_cpus: 0
  - name: ReceiverHelmsman
    num_replicas: 1
    ray_actor_options:
      num_cpus: 0
